apiVersion: v2
# 'appVersion' is set by the build process to the correct value
appVersion: '2.24.2-branch.testing4.384831-252a244'
description: Speckle Server
home: 'https://speckle.systems/'
icon: 'https://app.speckle.systems/images/logo.png'
maintainers:
  - name: Speckle Systems
    url: 'https://speckle.systems/'
name: speckle-server-branch-testing4
sources:
  - 'https://github.com/specklesystems/speckle-server'
type: application
# 'version' is set by the build process to the correct value
version: 2.24.2-branch.testing4.384831-252a244
