apiVersion: v1
kind: Service
metadata:
  name: {{ include "speckle-preview-service.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "speckle-preview-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "speckle-preview-service.selectorLabels" . | nindent 4 }}
