{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "speckle-preview-service.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "speckle-preview-service.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: false
{{- with .Values.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml . | nindent 8 }}
{{- end }}
secrets:
  - name: {{ .Values.redis.connectionString.secretName }}
{{- end }}
