{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "speckle-preview-service.serviceAccountName" . }}
  labels:
    {{- include "speckle-preview-service.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: false
secrets:
  - name: {{ .Values.redis.connectionString.secretName }}
{{- end }}
